export const expectedData = {
  id: "zgdpleOZe9AGppHZ0MLKY",
  city: "Hrodna, BY",
  chosenWeatherApi: "openWeatherApi",
  description: "Overcast clouds",
  lastUpdate: "2023-08-09T19:52:46.534Z",
  icon: "https://openweathermap.org/img/wn/04n@2x.png",
  iconId: "04n",
  timezone: 10800,
  temp: "13",
  humidity: 90,
  feelsLike: "13",
  pressure: 1017,
  wind: "3",
  visibility: 10000,
  list: [
    {
      id: "D2kP1-cUlzYZt2Vbj2zrO",
      day: "Wednesday",
      calendarDay: "Aug 9",
      description: "Light rain",
      icon: "https://openweathermap.org/img/wn/10n@2x.png",
      temp: "13",
      tempMin: "13",
    },
    {
      id: "1GiR2sUIQnD3aTD9ORt_e",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Light rain",
      icon: "https://openweathermap.org/img/wn/10n@2x.png",
      temp: "13",
      tempMin: "13",
    },
    {
      id: "arlk6fdNeladEL1QP9fTZ",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "12",
      tempMin: "12",
    },
    {
      id: "zWzF574xrGUBke3CtezSF",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "14",
      tempMin: "14",
    },
    {
      id: "qx7qcOlCxnv9Ywahb8pdO",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "19",
      tempMin: "19",
    },
    {
      id: "VaCYrf05exm8w93Ck8QQ4",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "21",
      tempMin: "21",
    },
    {
      id: "t2Q4EwcydKX-e7caKzYq-",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "21",
      tempMin: "21",
    },
    {
      id: "55RSy3iiUYW2a6cJJLewj",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "17",
      tempMin: "17",
    },
    {
      id: "NhWS6KR9QjGw43EQTMfrC",
      day: "Thursday",
      calendarDay: "Aug 10",
      description: "Light rain",
      icon: "https://openweathermap.org/img/wn/10n@2x.png",
      temp: "17",
      tempMin: "17",
    },
    {
      id: "g_lQG3A8pt3cziKpc-EuQ",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04n@2x.png",
      temp: "14",
      tempMin: "14",
    },
    {
      id: "uzsjTaFxN9wO5NsO7w1EH",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "15",
      tempMin: "15",
    },
    {
      id: "kVcjpJXSkuxgbhQFyThv_",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "16",
      tempMin: "16",
    },
    {
      id: "bpugZn3dkTsJvVVDVkr_C",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "20",
      tempMin: "20",
    },
    {
      id: "zeAv94HMLe0KxEYd9q1b3",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Broken clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "23",
      tempMin: "23",
    },
    {
      id: "-C_NMGlVSINIaAMW-Qe1E",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "22",
      tempMin: "22",
    },
    {
      id: "L782g-uQdn07GmXeDoG-5",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Broken clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "17",
      tempMin: "17",
    },
    {
      id: "ifGXrycezyL3Y1kD2K5yH",
      day: "Friday",
      calendarDay: "Aug 11",
      description: "Broken clouds",
      icon: "https://openweathermap.org/img/wn/04n@2x.png",
      temp: "15",
      tempMin: "15",
    },
    {
      id: "oAjAelxQ4iccUJsTeXOdC",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03n@2x.png",
      temp: "12",
      tempMin: "12",
    },
    {
      id: "-haCOmrWUwWhP41hdLaj4",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Clear sky",
      icon: "https://openweathermap.org/img/wn/01d@2x.png",
      temp: "11",
      tempMin: "11",
    },
    {
      id: "IBGqQFwZOKoJhqZKFZjVy",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Clear sky",
      icon: "https://openweathermap.org/img/wn/01d@2x.png",
      temp: "16",
      tempMin: "16",
    },
    {
      id: "MmF6cn9-kbOS2__UowAoa",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03d@2x.png",
      temp: "21",
      tempMin: "21",
    },
    {
      id: "ksWamEA_26ZRqGho6RpPj",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03d@2x.png",
      temp: "24",
      tempMin: "24",
    },
    {
      id: "R44epJZl74u4oQjsPqwph",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03d@2x.png",
      temp: "23",
      tempMin: "23",
    },
    {
      id: "OhQ-KHZs6aAd9T65UynTe",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Few clouds",
      icon: "https://openweathermap.org/img/wn/02d@2x.png",
      temp: "17",
      tempMin: "17",
    },
    {
      id: "7HoqRdzCMzjjXnZqRKUHw",
      day: "Saturday",
      calendarDay: "Aug 12",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03n@2x.png",
      temp: "14",
      tempMin: "14",
    },
    {
      id: "oCEum4ciyvBuTkTlapWIj",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03n@2x.png",
      temp: "13",
      tempMin: "13",
    },
    {
      id: "g9WXsmbpEscr9C4LD9VB2",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "13",
      tempMin: "13",
    },
    {
      id: "xYnm4Pb49aALX51W4otq7",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Broken clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "19",
      tempMin: "19",
    },
    {
      id: "Izx8AvFwnNW1Ppa-WhLqH",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03d@2x.png",
      temp: "24",
      tempMin: "24",
    },
    {
      id: "YsIiIYs5MBchQoIOUgt59",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Few clouds",
      icon: "https://openweathermap.org/img/wn/02d@2x.png",
      temp: "28",
      tempMin: "28",
    },
    {
      id: "tqlGo-n3igKIXNRncviLU",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Clear sky",
      icon: "https://openweathermap.org/img/wn/01d@2x.png",
      temp: "29",
      tempMin: "29",
    },
    {
      id: "Ds9R-x5oWfDP6RC9MFz_n",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03d@2x.png",
      temp: "24",
      tempMin: "24",
    },
    {
      id: "tlfJdYy47M9FmBKkRziMX",
      day: "Sunday",
      calendarDay: "Aug 13",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04n@2x.png",
      temp: "22",
      tempMin: "22",
    },
    {
      id: "ZpsCYdNCseQZQ22mrxUFh",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Overcast clouds",
      icon: "https://openweathermap.org/img/wn/04n@2x.png",
      temp: "22",
      tempMin: "22",
    },
    {
      id: "gTxhyw3g0erxlHpsI0wwl",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Scattered clouds",
      icon: "https://openweathermap.org/img/wn/03n@2x.png",
      temp: "19",
      tempMin: "19",
    },
    {
      id: "35g38s4Ql_1oC-htnC6ov",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Broken clouds",
      icon: "https://openweathermap.org/img/wn/04d@2x.png",
      temp: "24",
      tempMin: "24",
    },
    {
      id: "h-_T4tgadHB0kiCNlGurl",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Few clouds",
      icon: "https://openweathermap.org/img/wn/02d@2x.png",
      temp: "30",
      tempMin: "30",
    },
    {
      id: "CVGqKcWsmZY9XbHDm7O0L",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Clear sky",
      icon: "https://openweathermap.org/img/wn/01d@2x.png",
      temp: "32",
      tempMin: "32",
    },
    {
      id: "OWDcCkeR8k47zRKNaAsK8",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Few clouds",
      icon: "https://openweathermap.org/img/wn/02d@2x.png",
      temp: "32",
      tempMin: "32",
    },
    {
      id: "B-rrA8GfK-ED6b8ClZBVB",
      day: "Monday",
      calendarDay: "Aug 14",
      description: "Few clouds",
      icon: "https://openweathermap.org/img/wn/02n@2x.png",
      temp: "26",
      tempMin: "26",
    },
  ],
};
