import { WeatherList } from "../../../../../types/weather/weather";

export const mockData: WeatherList[] = [
  {
    id: "CDJVgm64pjy7JKjAwV9PT",
    day: "Wednesday",
    calendarDay: "Aug 2",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "24",
    tempMin: "23",
  },
  {
    id: "VFAKhBdi1ZERGzGbEeG_X",
    day: "Wednesday",
    calendarDay: "Aug 2",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "21",
    tempMin: "21",
  },
  {
    id: "71BusCOdJPWMF3MUiE1zX",
    day: "Wednesday",
    calendarDay: "Aug 2",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04n@2x.png",
    temp: "19",
    tempMin: "19",
  },
  {
    id: "SHNWJcqHMpkApb2-soa3V",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04n@2x.png",
    temp: "18",
    tempMin: "18",
  },
  {
    id: "hlEVGsnzy2VzqfmTPQqOO",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "17",
    tempMin: "17",
  },
  {
    id: "N2-N8qY5bUFP3prb5Tczv",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "19",
    tempMin: "19",
  },
  {
    id: "YDgkaKFuSkad5pMqxnITp",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "24",
    tempMin: "24",
  },
  {
    id: "2i_F1AXhO5HXDcacLti0U",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "21",
    tempMin: "21",
  },
  {
    id: "MhRLYAwrrwtnus4vm8Kxb",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "22",
    tempMin: "22",
  },
  {
    id: "uVFGfIhbfdeVqGgiKn3gi",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "20",
    tempMin: "20",
  },
  {
    id: "kDVX8o7JMHigDCgM0y1nJ",
    day: "Thursday",
    calendarDay: "Aug 3",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10n@2x.png",
    temp: "17",
    tempMin: "17",
  },
  {
    id: "k8WunoxFU2MWiuiRF2G7_",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04n@2x.png",
    temp: "16",
    tempMin: "16",
  },
  {
    id: "fE23IeYpf5_Lj2jq3x_87",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Scattered clouds",
    icon: "https://openweathermap.org/img/wn/03d@2x.png",
    temp: "14",
    tempMin: "14",
  },
  {
    id: "Uk0ouubf6pd1-1pG65JqJ",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Few clouds",
    icon: "https://openweathermap.org/img/wn/02d@2x.png",
    temp: "20",
    tempMin: "20",
  },
  {
    id: "jMpJ3LdVfkK3MEoLK4u8j",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "24",
    tempMin: "24",
  },
  {
    id: "2mxtEkItaeZiCtnM9MouY",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "27",
    tempMin: "27",
  },
  {
    id: "XT-dzsOERUQJ0kDkON1Vz",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "27",
    tempMin: "27",
  },
  {
    id: "SEibJCI9BsFBWRyLROokX",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "22",
    tempMin: "22",
  },
  {
    id: "qzujMDLtRz0vzvGN5YmJS",
    day: "Friday",
    calendarDay: "Aug 4",
    description: "Scattered clouds",
    icon: "https://openweathermap.org/img/wn/03n@2x.png",
    temp: "18",
    tempMin: "18",
  },
  {
    id: "081dGLo1XEqiTb3X7zhw4",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Few clouds",
    icon: "https://openweathermap.org/img/wn/02n@2x.png",
    temp: "16",
    tempMin: "16",
  },
  {
    id: "senA_4EAEu5RCcJlpP47X",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "15",
    tempMin: "15",
  },
  {
    id: "rX2kKE8_9KZ_g4bSMR-Gm",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "21",
    tempMin: "21",
  },
  {
    id: "LUn4C44dXX4e9Fqzgd12V",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "26",
    tempMin: "26",
  },
  {
    id: "6lNJUsgX9Np3z_ehY6nxN",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "22",
    tempMin: "22",
  },
  {
    id: "71sKA08RhfsWbvrqpF-7X",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "25",
    tempMin: "25",
  },
  {
    id: "FGzcj6T0PP0JtrmdcZY11",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "23",
    tempMin: "23",
  },
  {
    id: "lcQwoleYSIV4qbShBnznU",
    day: "Saturday",
    calendarDay: "Aug 5",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10n@2x.png",
    temp: "21",
    tempMin: "21",
  },
  {
    id: "JThfVBlrXomfunkcplW0u",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10n@2x.png",
    temp: "20",
    tempMin: "20",
  },
  {
    id: "1GNLwguoKkqy2zpDmnhTY",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "19",
    tempMin: "19",
  },
  {
    id: "pmpFMrsWxAsa96VA9ZoCy",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "21",
    tempMin: "21",
  },
  {
    id: "3K3k0jrMQ0-5RRjvXYXyk",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "24",
    tempMin: "24",
  },
  {
    id: "euYNlLWjMb0Oo6y8oZ4bl",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Broken clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "20",
    tempMin: "20",
  },
  {
    id: "LicbfS8uZZOHYSFFldxbk",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "18",
    tempMin: "18",
  },
  {
    id: "OMQFsmNyplYqmbkS2h73M",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "16",
    tempMin: "16",
  },
  {
    id: "UhhsTRsOIcWWTKOdA0Bwr",
    day: "Sunday",
    calendarDay: "Aug 6",
    description: "Moderate rain",
    icon: "https://openweathermap.org/img/wn/10n@2x.png",
    temp: "15",
    tempMin: "15",
  },
  {
    id: "cCqkUFRwNSIcqBF_loPfb",
    day: "Monday",
    calendarDay: "Aug 7",
    description: "Heavy intensity rain",
    icon: "https://openweathermap.org/img/wn/10n@2x.png",
    temp: "15",
    tempMin: "15",
  },
  {
    id: "5K143PvCTjaoUoWP6Cg5i",
    day: "Monday",
    calendarDay: "Aug 7",
    description: "Moderate rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "14",
    tempMin: "14",
  },
  {
    id: "VlLKuzMXL0h9x0kdTV_2r",
    day: "Monday",
    calendarDay: "Aug 7",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "15",
    tempMin: "15",
  },
  {
    id: "EJ2vXAe5gy0evvzgSJWG1",
    day: "Monday",
    calendarDay: "Aug 7",
    description: "Overcast clouds",
    icon: "https://openweathermap.org/img/wn/04d@2x.png",
    temp: "19",
    tempMin: "19",
  },
  {
    id: "b4d64CB7vEXBXgPbCrbP-",
    day: "Monday",
    calendarDay: "Aug 7",
    description: "Light rain",
    icon: "https://openweathermap.org/img/wn/10d@2x.png",
    temp: "20",
    tempMin: "20",
  },
];
