export const weatherApiPayload = {
  location: {
    name: "Brest",
    region: "Istarska",
    country: "Croatia",
    lat: 45.33,
    lon: 14.16,
    tz_id: "Europe/Zagreb",
    localtime_epoch: 1694765364,
    localtime: "2023-09-15 10:09",
  },
  current: {
    last_updated_epoch: 1694764800,
    last_updated: "2023-09-15 10:00",
    temp_c: 24,
    temp_f: 75.2,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_degree: 68,
    wind_dir: "ENE",
    pressure_mb: 1019,
    pressure_in: 30.09,
    precip_mm: 0.1,
    precip_in: 0,
    humidity: 61,
    cloud: 0,
    feelslike_c: 25.7,
    feelslike_f: 78.2,
    vis_km: 10,
    vis_miles: 6,
    uv: 4,
    gust_mph: 6.3,
    gust_kph: 10.1,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-09-15",
        date_epoch: 1694736000,
        day: {
          maxtemp_c: 23.2,
          maxtemp_f: 73.8,
          mintemp_c: 14.2,
          mintemp_f: 57.6,
          avgtemp_c: 18,
          avgtemp_f: 64.3,
          maxwind_mph: 6.9,
          maxwind_kph: 11.2,
          totalprecip_mm: 1.3,
          totalprecip_in: 0.05,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 4,
        },
        astro: {
          sunrise: "06:40 AM",
          sunset: "07:14 PM",
          moonrise: "06:47 AM",
          moonset: "07:36 PM",
          moon_phase: "Waxing Crescent",
          moon_illumination: "0",
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1694728800,
            time: "2023-09-15 00:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 37,
            wind_dir: "NE",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 31,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13,
            gust_kph: 20.9,
            uv: 1,
          },
          {
            time_epoch: 1694732400,
            time: "2023-09-15 01:00",
            temp_c: 14.3,
            temp_f: 57.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 34,
            wind_dir: "NE",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 33,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 14.3,
            heatindex_f: 57.7,
            dewpoint_c: 12.4,
            dewpoint_f: 54.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.6,
            gust_kph: 22,
            uv: 1,
          },
          {
            time_epoch: 1694736000,
            time: "2023-09-15 02:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 34,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 33,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 12.4,
            dewpoint_f: 54.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 1,
          },
          {
            time_epoch: 1694739600,
            time: "2023-09-15 03:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 40,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 33,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1,
          },
          {
            time_epoch: 1694743200,
            time: "2023-09-15 04:00",
            temp_c: 14.3,
            temp_f: 57.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 26,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 14.3,
            heatindex_f: 57.7,
            dewpoint_c: 12.4,
            dewpoint_f: 54.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.1,
            uv: 1,
          },
          {
            time_epoch: 1694746800,
            time: "2023-09-15 05:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 39,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 29,
            feelslike_c: 13.8,
            feelslike_f: 56.8,
            windchill_c: 13.8,
            windchill_f: 56.8,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 12.5,
            dewpoint_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1,
          },
          {
            time_epoch: 1694750400,
            time: "2023-09-15 06:00",
            temp_c: 14.5,
            temp_f: 58.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 38,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 27,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 14.5,
            heatindex_f: 58.1,
            dewpoint_c: 12.6,
            dewpoint_f: 54.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1,
          },
          {
            time_epoch: 1694754000,
            time: "2023-09-15 07:00",
            temp_c: 15.3,
            temp_f: 59.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 39,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 22,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15.3,
            heatindex_f: 59.5,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 5,
          },
          {
            time_epoch: 1694757600,
            time: "2023-09-15 08:00",
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 25,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 13.6,
            dewpoint_f: 56.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 5,
          },
          {
            time_epoch: 1694761200,
            time: "2023-09-15 09:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 51,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 74,
            cloud: 28,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 5,
          },
          {
            time_epoch: 1694764800,
            time: "2023-09-15 10:00",
            temp_c: 24,
            temp_f: 75.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 68,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 61,
            cloud: 0,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 4,
          },
          {
            time_epoch: 1694768400,
            time: "2023-09-15 11:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 73,
            wind_dir: "ENE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 67,
            cloud: 84,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 4,
          },
          {
            time_epoch: 1694772000,
            time: "2023-09-15 12:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 124,
            wind_dir: "SE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 66,
            cloud: 62,
            feelslike_c: 19.6,
            feelslike_f: 67.3,
            windchill_c: 19.6,
            windchill_f: 67.3,
            heatindex_c: 19.6,
            heatindex_f: 67.3,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.9,
            gust_kph: 4.7,
            uv: 4,
          },
          {
            time_epoch: 1694775600,
            time: "2023-09-15 13:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 67,
            cloud: 56,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.6,
            gust_kph: 2.5,
            uv: 4,
          },
          {
            time_epoch: 1694779200,
            time: "2023-09-15 14:00",
            temp_c: 22.3,
            temp_f: 72.1,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 68,
            cloud: 72,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 0,
            chance_of_rain: 64,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 1.6,
            gust_kph: 2.5,
            uv: 5,
          },
          {
            time_epoch: 1694782800,
            time: "2023-09-15 15:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 132,
            wind_dir: "SE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 67,
            cloud: 70,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.1,
            gust_kph: 1.8,
            uv: 5,
          },
          {
            time_epoch: 1694786400,
            time: "2023-09-15 16:00",
            temp_c: 22.2,
            temp_f: 72,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 180,
            wind_dir: "S",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 69,
            cloud: 72,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.3,
            gust_kph: 2.2,
            uv: 5,
          },
          {
            time_epoch: 1694790000,
            time: "2023-09-15 17:00",
            temp_c: 21.5,
            temp_f: 70.7,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 83,
            wind_dir: "E",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 76,
            cloud: 58,
            feelslike_c: 21.5,
            feelslike_f: 70.7,
            windchill_c: 21.5,
            windchill_f: 70.7,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 17.1,
            dewpoint_f: 62.8,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.4,
            gust_kph: 0.7,
            uv: 5,
          },
          {
            time_epoch: 1694793600,
            time: "2023-09-15 18:00",
            temp_c: 19.8,
            temp_f: 67.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 45,
            wind_dir: "NE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 39,
            feelslike_c: 19.8,
            feelslike_f: 67.6,
            windchill_c: 19.8,
            windchill_f: 67.6,
            heatindex_c: 19.8,
            heatindex_f: 67.6,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 5,
          },
          {
            time_epoch: 1694797200,
            time: "2023-09-15 19:00",
            temp_c: 18.8,
            temp_f: 65.8,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 84,
            cloud: 88,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 16,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 66,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 4,
          },
          {
            time_epoch: 1694800800,
            time: "2023-09-15 20:00",
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 22,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 21,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
          {
            time_epoch: 1694804400,
            time: "2023-09-15 21:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 25,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 17,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1,
          },
          {
            time_epoch: 1694808000,
            time: "2023-09-15 22:00",
            temp_c: 17.5,
            temp_f: 63.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 29,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 16,
            feelslike_c: 17.5,
            feelslike_f: 63.5,
            windchill_c: 17.5,
            windchill_f: 63.5,
            heatindex_c: 17.5,
            heatindex_f: 63.5,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 1,
          },
          {
            time_epoch: 1694811600,
            time: "2023-09-15 23:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 22,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 18,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-09-16",
        date_epoch: 1694822400,
        day: {
          maxtemp_c: 23.6,
          maxtemp_f: 74.5,
          mintemp_c: 14.1,
          mintemp_f: 57.4,
          avgtemp_c: 18.5,
          avgtemp_f: 65.4,
          maxwind_mph: 5.6,
          maxwind_kph: 9,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 75,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 5,
        },
        astro: {
          sunrise: "06:41 AM",
          sunset: "07:12 PM",
          moonrise: "07:52 AM",
          moonset: "07:51 PM",
          moon_phase: "Waxing Crescent",
          moon_illumination: "1",
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1694815200,
            time: "2023-09-16 00:00",
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 30,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 17,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 13,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1,
          },
          {
            time_epoch: 1694818800,
            time: "2023-09-16 01:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 17,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1,
          },
          {
            time_epoch: 1694822400,
            time: "2023-09-16 02:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 25,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 14,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 11.3,
            dewpoint_f: 52.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1,
          },
          {
            time_epoch: 1694826000,
            time: "2023-09-16 03:00",
            temp_c: 14,
            temp_f: 57.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 18,
            feelslike_c: 13.8,
            feelslike_f: 56.8,
            windchill_c: 13.8,
            windchill_f: 56.8,
            heatindex_c: 14,
            heatindex_f: 57.2,
            dewpoint_c: 11.2,
            dewpoint_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1,
          },
          {
            time_epoch: 1694829600,
            time: "2023-09-16 04:00",
            temp_c: 13.8,
            temp_f: 56.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 18,
            feelslike_c: 13.6,
            feelslike_f: 56.5,
            windchill_c: 13.6,
            windchill_f: 56.5,
            heatindex_c: 13.8,
            heatindex_f: 56.8,
            dewpoint_c: 11.1,
            dewpoint_f: 52,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1,
          },
          {
            time_epoch: 1694833200,
            time: "2023-09-16 05:00",
            temp_c: 13.8,
            temp_f: 56.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 30,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 18,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 13.8,
            heatindex_f: 56.8,
            dewpoint_c: 11,
            dewpoint_f: 51.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1694836800,
            time: "2023-09-16 06:00",
            temp_c: 13.8,
            temp_f: 56.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 29,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 19,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            windchill_c: 13.7,
            windchill_f: 56.7,
            heatindex_c: 13.8,
            heatindex_f: 56.8,
            dewpoint_c: 10.9,
            dewpoint_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1694840400,
            time: "2023-09-16 07:00",
            temp_c: 15.3,
            temp_f: 59.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 33,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 17,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15.3,
            heatindex_f: 59.5,
            dewpoint_c: 11.7,
            dewpoint_f: 53.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 5,
          },
          {
            time_epoch: 1694844000,
            time: "2023-09-16 08:00",
            temp_c: 17.5,
            temp_f: 63.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 39,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 14,
            feelslike_c: 17.5,
            feelslike_f: 63.5,
            windchill_c: 17.5,
            windchill_f: 63.5,
            heatindex_c: 17.5,
            heatindex_f: 63.5,
            dewpoint_c: 12.2,
            dewpoint_f: 54,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 5,
          },
          {
            time_epoch: 1694847600,
            time: "2023-09-16 09:00",
            temp_c: 19.2,
            temp_f: 66.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 205,
            wind_dir: "SSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 64,
            cloud: 17,
            feelslike_c: 19.2,
            feelslike_f: 66.6,
            windchill_c: 19.2,
            windchill_f: 66.6,
            heatindex_c: 19.2,
            heatindex_f: 66.6,
            dewpoint_c: 12.2,
            dewpoint_f: 54,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.3,
            gust_kph: 2.2,
            uv: 5,
          },
          {
            time_epoch: 1694851200,
            time: "2023-09-16 10:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 22,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 5,
          },
          {
            time_epoch: 1694854800,
            time: "2023-09-16 11:00",
            temp_c: 20.2,
            temp_f: 68.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 211,
            wind_dir: "SSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 25,
            feelslike_c: 20.2,
            feelslike_f: 68.4,
            windchill_c: 20.2,
            windchill_f: 68.4,
            heatindex_c: 20.2,
            heatindex_f: 68.4,
            dewpoint_c: 12.2,
            dewpoint_f: 54,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 6,
          },
          {
            time_epoch: 1694858400,
            time: "2023-09-16 12:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 207,
            wind_dir: "SSW",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 22,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 6,
          },
          {
            time_epoch: 1694862000,
            time: "2023-09-16 13:00",
            temp_c: 20.3,
            temp_f: 68.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 17,
            feelslike_c: 20.3,
            feelslike_f: 68.5,
            windchill_c: 20.3,
            windchill_f: 68.5,
            heatindex_c: 20.3,
            heatindex_f: 68.5,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 6,
          },
          {
            time_epoch: 1694865600,
            time: "2023-09-16 14:00",
            temp_c: 23,
            temp_f: 73.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 226,
            wind_dir: "SW",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 22,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 23,
            windchill_f: 73.4,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 6,
          },
          {
            time_epoch: 1694869200,
            time: "2023-09-16 15:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 26,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 6,
          },
          {
            time_epoch: 1694872800,
            time: "2023-09-16 16:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 19,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 6,
          },
          {
            time_epoch: 1694876400,
            time: "2023-09-16 17:00",
            temp_c: 20.8,
            temp_f: 69.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 169,
            wind_dir: "S",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 13,
            feelslike_c: 20.8,
            feelslike_f: 69.4,
            windchill_c: 20.8,
            windchill_f: 69.4,
            heatindex_c: 20.8,
            heatindex_f: 69.4,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.1,
            gust_kph: 1.8,
            uv: 6,
          },
          {
            time_epoch: 1694880000,
            time: "2023-09-16 18:00",
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 0.7,
            wind_kph: 1.1,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 18,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 5,
          },
          {
            time_epoch: 1694883600,
            time: "2023-09-16 19:00",
            temp_c: 19,
            temp_f: 66.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 30,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 18,
            feelslike_c: 19,
            feelslike_f: 66.2,
            windchill_c: 19,
            windchill_f: 66.2,
            heatindex_c: 19,
            heatindex_f: 66.2,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 5,
          },
          {
            time_epoch: 1694887200,
            time: "2023-09-16 20:00",
            temp_c: 18.8,
            temp_f: 65.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 20,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1694890800,
            time: "2023-09-16 21:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 6,
            wind_dir: "N",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 25,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 18.6,
            heatindex_f: 65.5,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1694894400,
            time: "2023-09-16 22:00",
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 356,
            wind_dir: "N",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 16,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 18.4,
            heatindex_f: 65.1,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1694898000,
            time: "2023-09-16 23:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 9,
            wind_dir: "N",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 21,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 1,
          },
        ],
      },
    ],
  },
};
