import { WeatherTransformedData } from "../../../../../../types/weather/weather";

export const openWeatherApimockData: WeatherTransformedData = {
  id: "1",
  city: "New York",
  chosenWeatherApi: "openWeatherApi",
  description: "Sunny",
  lastUpdate: new Date(),
  icon: "sun",
  iconId: "01d",
  timezone: -240,
  tzId: "",
  temp: "25°C",
  humidity: 50,
  feelsLike: "28°C",
  pressure: 1012,
  wind: "5 m/s",
  visibility: 10,
  list: [],
};

export const weatherApiMockData: WeatherTransformedData = {
  id: "1",
  city: "New York",
  chosenWeatherApi: "weatherApi",
  description: "Sunny",
  lastUpdate: new Date(),
  icon: "sun",
  iconId: "01d",
  timezone: undefined,
  tzId: "America/New_York",
  temp: "25°C",
  humidity: 50,
  feelsLike: "28°C",
  pressure: 1012,
  wind: "5 m/s",
  visibility: 10,
  list: [],
};

export const noTimezoneData: WeatherTransformedData = {
  id: "1",
  city: "New York",
  chosenWeatherApi: "api",
  description: "Sunny",
  lastUpdate: new Date(),
  icon: "sun",
  iconId: "01d",
  timezone: undefined,
  tzId: undefined,
  temp: "25°C",
  humidity: 50,
  feelsLike: "28°C",
  pressure: 1012,
  wind: "5 m/s",
  visibility: 10,
  list: [],
};
